### PR TITLE
bump 5.9.0 -> 5.10.0

### PR DESCRIPTION
**Pull request by urfolomeus**
Covers PRs #247, #248 and #250.

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
it will be helpful to add the Dough PR reference here please @urfolomeus

**Comment by urfolomeus** [comment]
Oops! Good shout! Added to description :)

**Comment by Tr4pSt3R** [comment]
:+1: since all the Frontend kings have already upvoted it

**Comment by munckymagik** [comment]
:+1:

**Pull request merged**
