### PR TITLE
[DEV APPROVED] Dough mediaQueries bug fixes x2 + 1x feature

### PR DESCRIPTION
**Pull request by nmiddleweek**
* getSize() function was returning ""mq-s"" instead of "mq-s". I'm stripping the extra double quotes away to allow it's internal atSmallViewport() to work correctly.

* init() function wasn't appending the testElement to the BODY tag correctly because it was writing it's value to a parameter variable.

* Added an updatePageClass() function which writes the current mq- mediaquery value to the HTML tag so we can use these as prefixes in our SCSS to better support mediaQuery aware components.

### CODE REVIEW

**Comment by munckymagik** [comment]
Anything we can add to `spec/js/tests/mediaQueries_spec.js` to prevent regression?

**Comment by nmiddleweek** [comment]
Yes sure, I've just checked the tests for mediaQueries and it was only testing for a situation where that function returns false instead of the actual string value. To test this properly, we'd need to force the Phantom browser viewPort to say 200px and then expect the value returned to be "mq-xs".

**Comment by slaywell** [comment]
This looks good to me :+1: @nmiddleweek and I will work on the varying screen size Karma tests as a separate PR.

**Comment by munckymagik** [comment]
Understood :+1:

**Pull request merged**
