### PR TITLE
Removes broken attribute interpolation

### PR DESCRIPTION
**Pull request by benlovell**
Dough's idea of interpolating model attribute names into the validation
messages was unfortunately somewhat misleading.

By default rails *does not* include the attribute name in the message. You can
however retrieve the message with attribute name by requesting
`errors#full_messages` or `errors#full_messages_for(:attrib)`.

If the expected behaviour is that we always return the full message including
attribute name we should respect rails' approach rather than butchering the
locale files to achieve the same ends. This PR brings us back to that behaviour
but may well introduce breaking changes to code that depended on it prior hence
the significant version bump.

If you need entirely custom error messages, that is - messages without their
associated attribute name interpolated - you should add your errors to `:base`

### CODE REVIEW

**Comment by benlovell** [comment]
@asmega @baphled

**Comment by baphled** [comment]
:+1: for respecting the Rails way

**Comment by asmega** [comment]
So this will unbreak the Rails API although fully customisable error messages on an attribute will no longer be possible.

I'm fine with adding them to base although this will mean those error messages will no longer be associated with a field and therefore won't be associated with the html form field.

@benlovell You can probably remove the entire `config/locales/en.yml` file and the specs should still pass.

:+1:

**Comment by benlovell** [comment]
I'll definitely concede this is still far from ideal in terms of what we actually *want*. Between the three of us I'm sure we can come up with something more appropriate. Let's talk on it when we're all back in the office but for now I'll get this one merged.

**Pull request merged**
