### PR TITLE
Fixes missing text in TabSelector - Dough issue #214

### PR DESCRIPTION
**Pull request by ourmaninamsterdam**
See #214 for background information.

@moneyadviceservice/frontend

### CODE REVIEW

**Comment by ourmaninamsterdam** [comment]
https://github.com/moneyadviceservice/frontend/pull/928

**Comment by benbarnett** [comment]
I think this works well, its generic enough for the 'default' theme of Dough, and can be overridden where needed by Yeast/frontend. 

One thing, can we bump the minor version on this? Feels like its worth noting "adding typography mixin"

**Comment by ourmaninamsterdam** [comment]
@benbarnett Version bumped

**Comment by benbarnett** [comment]
Nice. :+1:

**Comment by Guntrisoft** [comment]
:+1: :

**Pull request merged**
