### PR TITLE
Unpinning SASS-Rails and updating Ruby version

### PR DESCRIPTION
**Pull request by slaywell**
I have removed the deprecated SCSS that meant we couldn't upgrade Sass-Rails in other PRs. This PR removes the pinning of Dough to a specific Sass-Rails version, allowing it to be upgraded.

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
@slaywell not all tools are friendly to any version of sass-rails above version 4. How will this be rectified? Will this have an adverse effect on those tools, please?

**Comment by slaywell** [comment]
@Tr4pSt3R In that case, the tools themselves should be pinned to a version of sass-rails, not Dough which is a shared library. I believe that I have refactored all of the SCSS deprecation warnings anyway, so all live tools should be fine with this.

**Comment by Tr4pSt3R** [comment]
@slaywell that's all goody good then :)

👍 👍

**Comment by Tr4pSt3R** [comment]
it's not passing the Travis tests because of some CI problems.

**Comment by jongilbraith** [comment]
👍

**Comment by tomas-stefano** [comment]
The Travis errors are related to the old ruby versions on the travis.yml. So can you remove the old versions and add the new versions on the Travis.yml? After this the PR will be good to merge.

**Comment by tomas-stefano** [comment]
Mainly just change this file: https://github.com/moneyadviceservice/dough/blob/master/.travis.yml

**Comment by slaywell** [comment]
@tomas-stefano All good 💚

**Comment by tomas-stefano** [comment]
Great! 🚢

**Pull request merged**
