### PR TITLE
[DEV APPROVED] - Add repo to Jenkins

### PR DESCRIPTION
**Pull request by osharpe**
https://moneyadviceservice.tpondemand.com/entity/8745

Changes required in order to add this application / project into Jenkins.

In addition, the test group in Gemfile has been updated: to include tzinfo-data and brakeman gems

### CODE REVIEW

**Comment by willhall88** [comment]
👍

**Comment by tomas-stefano** [comment]
Question, will Dough have both Travis and Jenkins running for each PRs?

**Comment by osharpe** [comment]
@tomas-stefano The first stage is to get the CI aspect working correctly as Jenkins will be use to eventually build and deploy changes. Whether we continue to use Travis for CI, I'm not sure at this point.

**Comment by tomas-stefano** [comment]
👍 👍

**Pull request merged**
